# Testing the gym-2048 0.2.6 environment

In [1]:
import numpy as np
import time
from IPython.display import clear_output

In [2]:
from envs import game2048_env

In [3]:
id_action_dict = {0 : "UP",
                  1 : "RIGHT",
                  2 : "DOWN",
                  3 : "LEFT"}

In [4]:
env = game2048_env.Game2048Env()
env.seed()

env.reset()
#env.render()

done = False
moves = 0
while not done:
    clear_output(wait=True)
    
    action = env.np_random.choice(range(4), 1).item()
    next_state, reward, done, info = env.step(action)
    moves += 1
    
    if info['illegal_move']:
        done = False
    print(info)
    
    print(f'Next Action: {id_action_dict[action]} \nReward: {reward}')
    env.render()
    
    time.sleep(.5)

print('\nTotal Moves: {}'.format(moves))

{'illegal_move': False, 'highest': 128}
Next Action: LEFT 
Reward: 16.0
Score: 1104.0
Highest: 128
[[  4  16   2   4]
 [ 16 128  32  16]
 [  8  16   2   4]
 [  4   2  16   2]]

Total Moves: 148


# Testing gym-2048

https://github.com/mllobet/gym-2048

**ATTENTION** : the gym version to use is **0.17.0**

In [1]:
import numpy as np
import time
from IPython.display import clear_output

In [2]:
import gym_2048

In [3]:
import gym

In [4]:
gym.__version__

'0.17.0'

In [ ]:
env = gym.make('game-2048-v0')
#env.seed()

state = env.reset()

done = False
moves = 0
while not done:
    clear_output(wait=True)
    
    valid_moves = np.where(env.moves_available())[0]
    
    action = np.random.choice(valid_moves, 1).item()
    next_state, reward, done, info = env.step(action)
    moves += 1
    
    #print(f'Next Action: {id_action_dict[action]} \nReward: {reward}')
    env.render('human')
    print(info)
    
    time.sleep(.5)

print('\nTotal Moves: {}'.format(moves))

0 0 0 0
0 0 0 0
0 0 0 4
4 2 0 2
Score: 0
Move: 2
{'score': 0, 'won': False}
